"""
Django settings for modulos_consultas project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-+&@@eu+4t03l@$wx4yh%6_0vg%%f#7(^d-=ntc+8#y3lt_cnhr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Permitir acceso desde cualquier host (útil para desarrollo en red local)
# Para producción, especifica los hosts permitidos explícitamente
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*,localhost,127.0.0.1', cast=Csv())

# ==============================================================================
# SECURITY SETTINGS - CSRF Protection
# ==============================================================================
# CSRF Trusted Origins - Permite solicitudes CSRF desde estos orígenes
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000,https://educonnect-lybu.onrender.com',
    cast=Csv()
)

# Configuración CSRF para desarrollo y producción
# En desarrollo (DEBUG=True) estas configuraciones son más permisivas
if not DEBUG:
    CSRF_COOKIE_SECURE = True  # Solo enviar cookie CSRF via HTTPS
    CSRF_COOKIE_HTTPONLY = False  # Permitir acceso en formularios
    CSRF_COOKIE_SAMESITE = 'Lax'  # Lax en lugar de Strict para evitar problemas cross-site
    SECURE_SSL_REDIRECT = True  # Redirigir todo a HTTPS
else:
    CSRF_COOKIE_SECURE = False  # Permitir HTTP en desarrollo
    CSRF_COOKIE_HTTPONLY = False  # Permitir acceso en desarrollo
    CSRF_COOKIE_SAMESITE = 'Lax'  # Más permisivo en desarrollo

# Tiempo de vida del token CSRF (segundos) - 1 año por defecto
CSRF_COOKIE_AGE = 31449600

# ==============================================================================
# SECURITY SETTINGS - SSL/HTTPS Configuration
# ==============================================================================
if not DEBUG:
    # Forzar redirección a HTTPS (solo en producción)
    SECURE_SSL_REDIRECT = True
    
    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies seguras (solo HTTPS)
    SESSION_COOKIE_SECURE = True
    
    # Protección contra clickjacking
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Proxy headers para HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Configuración para desarrollo
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Más permisivo para desarrollo

# ==============================================================================
# SESSION SETTINGS
# ==============================================================================
SESSION_COOKIE_NAME = 'educonnect_sessionid'
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'

# ==============================================================================
# SECURITY HEADERS
# ==============================================================================
# Política de referencia
SECURE_REFERRER_POLICY = 'same-origin'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'EduConnectApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'EduConnectApp.middleware.EnsureUsuarioSessionMiddleware',
    # 'EduConnectApp.middleware.RoleBasedAccessControlMiddleware',  # DESHABILITADO - conflicto con login
    'EduConnectApp.middleware.RateLimitMiddleware',  # Rate limiting
    'EduConnectApp.middleware.InputSanitizationMiddleware',  # Sanitización
    'EduConnectApp.middleware.SecurityHeadersMiddleware',  # Headers de seguridad
    'EduConnectApp.middleware.ActivityLogMiddleware',  # Logging
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'modulos_consultas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'modulos_consultas.wsgi.application'


USE_SQLITE = config('USE_SQLITE', default='0') == '1'
DATABASE_URL = config('DATABASE_URL', default='')

# Debug logging
import sys
print(f"\n{'='*60}", file=sys.stderr)
print(f"DATABASE CONFIGURATION DEBUG", file=sys.stderr)
print(f"{'='*60}", file=sys.stderr)
print(f"DATABASE_URL present: {bool(DATABASE_URL)}", file=sys.stderr)
print(f"DATABASE_URL value: {DATABASE_URL[:50] + '...' if DATABASE_URL and len(DATABASE_URL) > 50 else DATABASE_URL}", file=sys.stderr)
print(f"USE_SQLITE: {USE_SQLITE}", file=sys.stderr)
print(f"DEBUG mode: {DEBUG}", file=sys.stderr)
print(f"{'='*60}\n", file=sys.stderr)

# Priority: DATABASE_URL > USE_SQLITE > Environment variables > Default MySQL
if DATABASE_URL:
    # Para Render PostgreSQL o compatible - PRIORIDAD 1
    import dj_database_url
    print(f"Using: DATABASE_URL (Render PostgreSQL)", file=sys.stderr)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif USE_SQLITE:
    # SQLite para desarrollo local - PRIORIDAD 2
    print(f"Using: SQLite (Local Development)", file=sys.stderr)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Read DB credentials from environment variables - PRIORIDAD 3
    DB_ENGINE = config('DB_ENGINE', default='django.db.backends.postgresql')
    DB_NAME = config('DB_NAME', default='educonnect')
    DB_USER = config('DB_USER', default='educonnect_user')
    DB_PASSWORD = config('DB_PASSWORD', default='')
    DB_HOST = config('DB_HOST', default='localhost')
    DB_PORT = config('DB_PORT', default='5432')

    print(f"Using: Environment variables (DB_HOST={DB_HOST}, DB_PORT={DB_PORT})", file=sys.stderr)

    if 'postgresql' in DB_ENGINE or 'postgres' in DB_ENGINE:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': DB_NAME,
                'USER': DB_USER,
                'PASSWORD': DB_PASSWORD,
                'HOST': DB_HOST,
                'PORT': DB_PORT,
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': DB_ENGINE,
                'NAME': DB_NAME,
                'USER': DB_USER,
                'PASSWORD': DB_PASSWORD,
                'HOST': DB_HOST,
                'PORT': DB_PORT,
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    'charset': 'utf8mb4',
                },
            }
        }

print(f"Database configured: {DATABASES['default']['ENGINE']}", file=sys.stderr)
print(f"{'='*60}\n", file=sys.stderr)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = config('STATIC_URL', default='/static/')

# Static root for collectstatic command (production)
STATIC_ROOT = BASE_DIR / config('STATIC_ROOT', default='staticfiles')

# Tell Django where to find additional static files that are not inside an app's
# "static/" subfolder. We keep a project-level `static/` directory for overrides
# and shared assets; include it here so the dev server and collectstatic will
# pick up files placed in the repository `static/` folder.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise para servir archivos estáticos en producción
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = config('MEDIA_URL', default='/media/')
MEDIA_ROOT = BASE_DIR / config('MEDIA_ROOT', default='media')

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Spectacular (OpenAPI) settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'EduConnect API',
    'DESCRIPTION': 'API documentation for EduConnectApp',
    'VERSION': '1.0.0',
}
