# Generated by Django 5.2.7 on 2025-10-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_asignatura', models.CharField(max_length=20, unique=True)),
                ('nombre_asignatura', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('semestre_recomendado', models.IntegerField(blank=True, null=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignaturas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionesSistema',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave_config', models.CharField(max_length=100, unique=True)),
                ('valor_config', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_dato', models.CharField(blank=True, max_length=7, null=True)),
                ('grupo_config', models.CharField(blank=True, max_length=50, null=True)),
                ('modificable_por_admin', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuraciones_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_docente', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_academico', models.CharField(blank=True, max_length=200, null=True)),
                ('especialidades', models.TextField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('horario_atencion', models.TextField(blank=True, null=True)),
                ('tiempo_respuesta_maximo', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docentes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estadistica', models.CharField(max_length=25)),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('datos_estadistica', models.JSONField()),
                ('fecha_calculo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estadisticas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('numero_matricula', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriasTemas',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('orden_visualizacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.asignaturas')),
            ],
            options={
                'db_table': 'categorias_temas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(blank=True, max_length=7, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_consulta', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_respuesta', models.DateTimeField(blank=True, null=True)),
                ('es_anonima', models.IntegerField(blank=True, null=True)),
                ('adjunto_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_consulta', models.CharField(blank=True, max_length=21, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.asignaturas')),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.categoriastemas')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.estudiantes')),
            ],
            options={
                'db_table': 'consultas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('contenido_respuesta', models.TextField()),
                ('tipo_respuesta', models.CharField(blank=True, max_length=17, null=True)),
                ('adjunto_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('tiempo_respuesta_horas', models.IntegerField(blank=True, null=True)),
                ('calificacion_respuesta', models.JSONField(blank=True, null=True)),
                ('es_respuesta_definitiva', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id_consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.consultas')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.docentes')),
            ],
            options={
                'db_table': 'respuestas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionesRespuesta',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.JSONField()),
                ('comentario_evaluacion', models.TextField(blank=True, null=True)),
                ('fue_util', models.IntegerField(blank=True, null=True)),
                ('resolvio_duda', models.IntegerField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.estudiantes')),
                ('id_respuesta', models.OneToOneField(db_column='id_respuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.respuestas')),
            ],
            options={
                'db_table': 'evaluaciones_respuesta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SesionesUsuario',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('token_sesion', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('activa', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios')),
            ],
            options={
                'db_table': 'sesiones_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimientos',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=10)),
                ('mensaje', models.TextField()),
                ('adjunto_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.consultas')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios')),
            ],
            options={
                'db_table': 'seguimientos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionPasswords',
            fields=[
                ('id_recuperacion', models.AutoField(primary_key=True, serialize=False)),
                ('token_recuperacion', models.CharField(max_length=255, unique=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('utilizado', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios')),
            ],
            options={
                'db_table': 'recuperacion_passwords',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=22)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('id_referencia', models.IntegerField(blank=True, null=True)),
                ('tipo_referencia', models.CharField(blank=True, max_length=10, null=True)),
                ('leida', models.IntegerField(blank=True, null=True)),
                ('enviada_email', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_destinatario', models.ForeignKey(db_column='id_usuario_destinatario', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios')),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogsActividad',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=18)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios')),
            ],
            options={
                'db_table': 'logs_actividad',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios'),
        ),
        migrations.CreateModel(
            name='ArchivosAdjuntos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('nombre_original', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('tamaño_bytes', models.BigIntegerField(blank=True, null=True)),
                ('tipo_referencia', models.CharField(max_length=11)),
                ('id_referencia', models.IntegerField()),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_subida', models.ForeignKey(db_column='id_usuario_subida', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.usuarios')),
            ],
            options={
                'db_table': 'archivos_adjuntos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id_docente_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_academico', models.CharField(blank=True, max_length=20, null=True)),
                ('grupo', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.asignaturas')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.DO_NOTHING, to='EduConnectApp.docentes')),
            ],
            options={
                'db_table': 'docente_asignatura',
                'managed': True,
                'unique_together': {('id_docente', 'id_asignatura', 'periodo_academico', 'grupo')},
            },
        ),
    ]
