# Generated by Django 5.2.7 on 2025-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduConnectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='adjunto_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='adjuntos/'),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='adjunto_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='adjuntos/'),
        ),
        migrations.AlterField(
            model_name='seguimientos',
            name='adjunto_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='adjuntos/'),
        ),
    ]
